### ISSUE TITLE
feature request, lumina-fm (insight): progress informations for copy and move commands

### ISSUE THREAD

**Issue by abelbabel** [lumina-desktop/lumina#201]
When moving or copying files it would be nice to have these informations
- relative amount of transferred data
- total amount of transferred data
- transfer rate
- transfer duration

additional this information with multiple file transfer
m/n with m and n being numbers and
m: which file is currently being transferred
n: how many files should be transferred totally

**Comment by beanpole135** [comment]
I just committed an update to the file manager where running operations will now get a status indication within a system tray icon *if* the operation lasts longer than 1 second.
The information contained within these status updates are:
 * Total number of file operations
 * Current file number (allowing percentages and/or status indicator)
 * Current File name/operation (example: Copying File1.txt -> File2.txt)

Note that this is still *file-based* for status updates instead of *data-based* as you request. Moving to a data-based status system might be possible later, but remember that adding additional watchers/statuses to each file-based operation could significantly slow down the overall transfer. We would have to be very careful about how to implement this type of update to ensure that the file operation still happens as fast as the hardware allows.

**Comment by q5sys** [comment]
I've started working on this and I've got some rough code in place (though inactive), hopefully by the public release of Lumina 2.0 well have this in place.
