### ISSUE TITLE
Luminome?

### ISSUE THREAD

**Issue by outpaddling** [lumina-desktop/lumina#563]
Have a curious cosmetic issue on a couple of servers.  I'm seeing a Gnome foot icon for the main menu button.  ( See attached. )  Where does it get the bitmap for this icon?
![screenshot-2018-01-03-16-30-03](https://user-images.githubusercontent.com/11299711/38209516-407577a6-367a-11e8-857c-7712cad9aa03.png)

**Comment by q5sys** [comment]
Which menu are you using?  We have three actually.  Open Lumina-Config and see what is listed as the first panel plugin.  
If you are using the user menu, you can change this to whatever you want. In Lumina-config under 'General Options' you can set this to be whatever you want. By default its  ```~/.loginIcon.png```.  My guess is that gnome overwrote that file.
If you are using the Start menu it should be the XDG icon for ```start-here-lumina```.
If you are using the application menu, it should also be the XDG icon for ```start-here-lumina```

**Comment by outpaddling** [comment]
Start menu.  I've never altered this from the default.  On another machine, I'm getting a different icon, blue circle around a white arrow.  I recognize it from an application I had installed, but I don't recall what it is.
How do I check the XDG icons?  Is there a way to protect the configuration from being overwritten?
![screenshot-2018-04-14-19-15-28](https://user-images.githubusercontent.com/11299711/38773742-d8d91c48-4019-11e8-995a-02f024f596a0.png)
![screenshot-2018-04-14-19-21-00](https://user-images.githubusercontent.com/11299711/38773743-d917409a-4019-11e8-8dbb-91a41c084ff3.png)

**Comment by beanpole135** [comment]
I have tracked this down, and it looks like something in Qt changed a bit with the recent move from Qt 5.7 to 5.9:
The icon for the start menu is supposed to be the "start-here-lumina" icon from the current theme, but when that icon does not exist in the theme, it looks like Qt is now loading the "start-here" icon (the foot from the Adwaita icon theme, or the play/circle icon from the Oxygen theme) rather than continuing on to look at the fallback theme and/or pixmap icon directory (older standard).
I have already been looking into this and may have found a way to tie the older pixmap directory into the theme specification so that Qt will find the proper icons now. This should be getting committed to TrueOS here soon.

**Comment by outpaddling** [comment]
Cool.  As you might have guessed from my screen shots, I'm running stock FreeBSD with the Lumina port.  
I'll watch for a fix to the port.  I use bleeding edge packages and update frequently, so I should see the fix shortly after it's committed.
FreeBSD outpaddling.cs  bacon ~ 1007: cat /usr/local/etc/pkg/repos/FreeBSD.confFreeBSD: {
  url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"
}
Thanks!
