### ISSUE TITLE
Power, disk and network management (D-Bus)

### ISSUE THREAD

**Issue by rodlie** [lumina-desktop/lumina#575]
So, been using Lumina for a couple of days now and I like it :)

Lumina currently does 90% of my needs (I only use core+core-utils), the "only" thing that's missing is power management, disk management and support for org.freedesktop.ScreenSaver(.SimulateUserActivity), and of course network (not an high priority for me).

First of, has this been implemented in v2.0 (I can only find vague articles online regarding v2) or planned for v1? Timeframe? what backends is/will be supported?

I have done work against HALD/D-Bus in the past, so adding a basic systray app for various D-Bus related services I need should not be a problem. I just don't want to waste resources creating something that's being worked on.

Note I'm an Linux user (former NetBSD) so my priorities will be Linux, are FreeBSD compatible with the newer udisk stuff? or is it even needed? Last time I used NetBSD HALD worked fine at least (some years ago though).

My plan for org.freedesktop.org.ScreenSaver was to just make a basic service that supports .SimulateUserActivity so that video players can inhibit the xscreensaver. Any plans/suggestions for this?

**Comment by rodlie** [comment]
So, I made a basic "device manager" with udisk2 as backend: https://github.com/rodlie/lumina-devices
Support notifications, mount, unmount of removable devices. Uses lumina-open for viewing contents after mount.
![lumina-devices](https://user-images.githubusercontent.com/34516798/38779709-4f424e4c-40cc-11e8-97ed-4336a9cec3da.png)

May contain bugs ;)

Btw, I can add support for hald if that's still used on the BSD's?

**Comment by rodlie** [comment]
Back again.... Created a DBus daemon for Lumina that enables freedesktop compatible applications (media players etc) to inhibit xscreensaver. Still work in progress, but supports org.freedesktop.Screensaver.SimulateUserActivity

Code: https://github.com/rodlie/lumina-dbus

**Comment by rodlie** [comment]
Nobody? Ok, I will do the work then :)

**Comment by q5sys** [comment]
> So, I made a basic "device manager" with udisk2 as backend: 
Looks neat.  Ken and I will look it over this week.   As for your HAL question, I know in the past we had talked about removing HAL from TrueOS due to security issues with it and that it is no longer maintained in FreeBSD, so at least in the mean time, I'd recommend not spend too much time on things that require it.  

> Created a DBus daemon for Lumina that enables freedesktop compatible applications (media players etc) to inhibit xscreensaver.

x-screensaver will be going away with Lumina v2, but I dont know how far off it will be till release.  I'll try to ducktape Ken to a chair next week so we can try to hammer out some overview milestones... so we can make a public statement about timeline, direction, plans, etc.  It's something we probably should have done by now already, but we've just not hunkered down to write it.

**Comment by rodlie** [comment]
Thanks for the information, v1 is good enough for me at this time, and I
have no problems coding for a legacy branch.

**Comment by beanpole135** [comment]
@rodlie : If you want to make specific "companion" utilities for Lumina I think that is excellent.
There is obviously no problem with building/running that app externally to Lumina itself, so what are you looking for us to do for you?
Since your app does not need/use the libLumina/core classes, I see no need to merge it into the lumina repository directly, so it really comes down to what you have planned for it. Are you looking to add it as a standalone repository within the lumina-desktop organization instead? If so, I think we can definitely work something out in that regard.

**Comment by rodlie** [comment]
My biggest problem with having a separate repository is that it's not seen as something users need, and it will not be used(?).

Btw, don't fork "rodlie/lumina-devices", I would prefer to merge that in "rodlie/lumina-dbus" together with other D-Bus stuff.

**Comment by rodlie** [comment]
So, I created a seperate repo https://github.com/rodlie/lumina-extra

I will merge my current utils there.

**Comment by rodlie** [comment]
The screensaver-service is now feature complete and working, been testing it for several days in CentOS/Slackware and I have not noticed any bugs. The disk-manager also seems stable, with support for removable disks and optical. I should add a settings app for disk-manager that let's users select default actions for various media (open music cd in X, open DVD in Y etc etc).

Next up is a power-manager.

off-topic: I also started a keyboard-manager, needs some UI love before done.

**Comment by rodlie** [comment]
Hi, again.

Small update. First of I was busy for a couple of weeks, so didn't get much done. But had some hours free yesterday to finish a "0.1" version of the power manager. Still stuff to do, but it support the basic functions.
![power-screenshot](https://user-images.githubusercontent.com/34516798/39807061-b197722c-537b-11e8-9363-918bbad4c606.png)

Currently the disk manager is missing a settings app, but other than that most common features for power and disk management is there (the keyboard manager is also feature complete).

Hopefully I will be done by the end of the week.

Btw, found another "papercut", see image with systray. The clock always get cropped somehow by switching windows or opening new ones, highly irritating (will check in the code).

**Comment by rodlie** [comment]
A small update.

I have currently stopped doing much in lumina-extra. Feature wise I'm happy, and since I don't have any feedback there's not much to do.

I have split out two components in lumina-extra to libdisks and libpower, for use in qtfm. I have also moved development of the "power stuff" to qtfm, but I will/can "bacport" any modifications that may be needed/wanted to lumina-extra if someone asks.

So for now I will close this.
