### ISSUE TITLE
Simple text viewer

### ISSUE THREAD

**Issue by q5sys** [lumina-desktop/lumina#601]
write one

**Comment by q5sys** [comment]
current state: https://github.com/q5sys/qtv

**Comment by beanpole135** [comment]
@q5sys : Go ahead and make it a separate repository under the lumina-desktop organization.
I am actually planning on taking all the desktop utilities out of the lumina repo and move them to individual repos as well sometime in the near future. Now that we have a whole lumina-desktop organization we can better manage the tools through different repos instead of the 1-repo limitation we had with Lumina when we were still under the PC-BSD/TrueOS organizations.

**Comment by q5sys** [comment]
Since the window manager is on hold till ${DATE}, Im going to eventually do the repo break apart but I'll save that for what will be 2.0 since it'll require a lot of rework for packagers.  So I'm merging this into the main repo like we have historically done and then break it back out later with all that work.
