### ISSUE TITLE
Panel left on the screen appears offset to the right (Trident)

### ISSUE THREAD

**Issue by madewo** [lumina-desktop/lumina#628]
I set the panel to the left. That works fine, but always after startup it appears offset by the width to the right.
With TrueOS it appeared offset too, but then moved to the left without intervention. With Trident I have to push it over every time.
![screenshot-2018-09-29-15-36-02](https://user-images.githubusercontent.com/21984477/46246620-f7215100-c400-11e8-99ca-d57a78cdc6e2.png)

**Comment by 9Panther** [comment]
I am having the same issue on Project Trident RC1
This issue only happens when the panel is on the left edge and is set to 100% Length, and you log out and log back in, or restart, or power off the computer. 

To recreate the bug: 
Preferences | All Desktop Settings | Panels | Panel 1 | Edge Left | Alignment Center | Size 54  pixels | 100% Length
Log out and log back in. 

The Panel will shift to the right, the thickness of the size of the panel. 
At 99% Length it has no issues 
Different sizes, effect the degree of shifting, a size of 10 will shift 10 pixels over, size of 50 will shift over by 50 pixels. 
Alignment Top/Left | Center | Bottom /Right | have no effect on the shifting.

Thanks
