### ISSUE TITLE
weblate.trueos.org is down (503 Service Unavailable)

### ISSUE THREAD

**Issue by scootergrisen** [lumina-desktop/lumina#647]
https://weblate.trueos.org/ is down (503 Service Unavailable) so i cant check the translations.
If the way to translate have changed then i suggest updatering the instructions so translators can know where to translate.

**Comment by q5sys** [comment]
Yea, we let the webteam know that probably 6 months ago.  Dont know if that'll ever get fixed again or not.  Since TrueOS is now shifting away from anything GUI, there's nothing for TrueOS to really worry about translating that isnt already handled by FreeBSD.  
I dont expect it will be fixed or turned back on in the future.
We probably need to spin up our own solution.  Ken and I have talked about this, and he does have an idea in mind, but there are so many other things that have taken focus since last April... that I dont think we have any idea when it will be done.

**Comment by beanpole135** [comment]
Lumina has a completely new website now that the iX web team is no longer involved.
No references to weblate remain that I could find.
