### ISSUE TITLE
systemtray dropbox icon doesn't appear

### ISSUE THREAD

**Issue by BrianA-MN** [lumina-desktop/lumina#654]
System - Slackware64 14.2 full install with Lumina -1.4.0.p1.  Dropbox install goes fine.   Dropbox.desktop icon appears on desktop.  dropbox autostart is added to preferences autostart and is selected.  However, no Dropbox icon appears in the systemtray.  I'm also running qtfm, which does put an icon in the systemtray of the default panel1. I added qtfm, because lumina-fm would not automount removable media.  Is there a service I need to run to have the Dropbox icon appear in the systemtray?

**Comment by rodlie** [comment]
You should try the master branch (1.4.0p1 is very old**). Dropbox works here (on Slackware 14.2 using a (very) custom version of Lumina).
![systray](https://user-images.githubusercontent.com/34516798/56099696-6e877f80-5f10-11e9-8421-f62ac947ced4.png)

Also try running /opt/dropbox/dropboxd from the terminal and see if you get any errors/warning etc.

**: maybe the project should do a release/tag soon? Distros will only ship the latest release, and that is 1.4.0p1. There has been many fixes since then.....

**Comment by BrianA-MN** [comment]
Thanks for the reply.  Closing due to age of comment and no longer applicable.
