### ISSUE TITLE
lumina-config mouse-settings invert-scroll-wheel

### ISSUE THREAD

**Issue by madewo** [lumina-desktop/lumina#661]
“Invert Scroll Wheel” checked or not does not change the scroll direction with the trackpad nor with an USB-Mouse.
BTW: I would prefer “Invert Scroll Direction” for a trackpad does not have a wheel nor is it possible to invert the scroll wheel of a mouse by software - it's the direction of scrolling that can be inverted.

**Comment by Kinouuu** [comment]
Same problem for me.

**Comment by q5sys** [comment]
we use the term 'wheel' because your on the mouse-settings page.
There is the possibility we will have a separate trackpad-settings page if the OS level utilities for it are developed. 
As for it being broken... I'll see if I can reproduce the behavior you're describing.

**Comment by beanpole135** [comment]
Lumina does not have a mouse configuration settings page in lumina-config.
On Project Trident / TrueOS / FreeBSD, that entry in lumina-config appears to just be a standard system registration/link to the "SysAdm" utility for configuring the "moused" service.
This issue should probably be redirected over to the FreeBSD project since they maintain the "moused" service and functionality.
