### ISSUE TITLE
lumina-pdf crashes on click in toc

### ISSUE THREAD

**Issue by hardcodes** [lumina-desktop/lumina#671]
I've opened a pdf file with

```
lumina-pdf gnupg.pdf
```
in the terminal so that I can see error messages. When I click on a link in the table of contents to a page inside the [pdf file](https://www.gnupg.org/documentation/manuals/gnupg.pdf), the program crahes with

```
Loading Locale: "l-pdf" "en_US" "UTF-8"
 - Document Setup : start loading pages now
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: i965
warning: assert: overwrite hash slot with different value!
warning: assert: overwrite hash slot with different value!
warning: assert: overwrite hash slot with different value!
[1]    92351 bus error  lumina-pdf gnupg.pdf
```

The same happens -- naturally -- when the file is opened with `lumina-open` or via the GUI but the error messages can not be seen.

```
/var/log/messages
```

shows
```
kernel: pid 58790 (lumina-pdf), uid 1001: exited on signal 11
```

or

```
kernel: pid 92351 (lumina-pdf), uid 1001: exited on signal 10
```

**Comment by beanpole135** [comment]
This appears to have been caused by the "mupdf" backend integrations within lumina-pdf, and are no longer impacting us since we switched back to the "poppler" backend recently (mupdf changed versions/libraries/API again - tired of trying to keep up with a project that is unable to provide a consistent library interface).
