### ISSUE TITLE
LXQT and other Questions

### ISSUE THREAD

**Issue by Mazaduk** [lumina-desktop/lumina#675]
Dear Ken Moore and Project Trident Team and TrueOS team,

I'd like to ask: 
- Why have you chosen to make a new lightweight DE instead of joining or forking the LXQT DE?
- What are the differences between GhostBSD and Project Trident (other than Mate vs Lumina)?
- Do you think you guys will attempt to integrate more OpenBSD features and code? What about some performance features/code from DragonflyBSD?
- As an operating systems and general technology newbie, how do you recommend someone go from scratch to making a code contribution to the TrueOS and other BSD projects?

Thanks,
Mazaduk

**Comment by q5sys** [comment]
I'll answer for myself, Ken can chime in as well if he wants.

1) Linux desktops are designed with Linux as the primary focus.  The BSD Devs have to go back later and tweak and change things so they will work on BSD.  There needed to be a desktop that was agnostic as to OS (Linux vs BSD) that would just work everywhere.
2) The Desktop Enviroments are not the only difference.  There are differences in configurations between the two.  Also, Trident uses the new TrueOS build framework, I dont believe GhostBSD is using that yet.
3) We are not going to be able to use any features that are kernel dependent, as we are using the TrueOS kernel which is a slightly modified FreeBSD kernel.  While I would love to bring in some of the OpenBSD and DragonflyBSD features, Im not a kernel dev.
4) Start small.  Find some small feature you'd like to add to a program or a small utility that does not exist that you think would be helpful.  Work on that.  After a while you will get more comfortable in your abilities and start to take on bigger tasks and bigger projects.

**Comment by Mazaduk** [comment]
Dear q5sys,
Regarding your last answer: Being as inexperienced as I am, it is easy to see that someone else may eventually create or code what I may have in mind - and they'll do it better than me (with cleaner code, docs, etc). It seems I would become an "obsolete" programmer if I were to work on small features, if the idea holds true that eventually those small features will eventually coded by someone who is more skilled etc. Is there no other way towards becoming a competent contributor, compared to this method of working on [seemingly] pointless, small, "homework-like" coding projects?
I suppose as a human being I can't do all I imagine...

**Comment by q5sys** [comment]
Many developers started by doing small things here and there, before eventually getting to the point where they can take on bigger projects.  You shouldn't count yourself out.  Big projects are built with a lot of smaller pieces.  And even if those small pieces get replaced in the future, its still a learning experience, both in you writing what you wrote, and you learning how it can be written better.

If you stop yourself from doing anything because someone might do it better in the future... you'll never get anything done. 

As for my avatar, I used to be a puppylinux dev before getting involved with Lumina.

FWIW, my first commit in Lumina was simply adding a keyboard shortcut into the file manager to hide/show files instead of having to use the menu item.

**Comment by beanpole135** [comment]
I think q5sys basically answered this completely - I don't really have anything else to add.
