### ISSUE TITLE
build failed.

### ISSUE THREAD

**Issue by dariusity** [lumina-desktop/lumina#680]
Hi, I was trying to build lumina from source, however halfway building I get this 
Cannot find file: /home/han/Downloads/lumina/src-qt5/desktop-utils/lumina-calculator/lumina-calculator.pro.
make[2]: *** [Makefile:155: sub-lumina-calculator-make_first] Error 2
make[2]: Leaving directory '/home/han/Downloads/lumina/src-qt5/desktop-utils'
make[1]: *** [Makefile:99: sub-desktop-utils-make_first] Error 2
make[1]: Leaving directory '/home/han/Downloads/lumina/src-qt5'
make: *** [Makefile:47: sub-src-qt5-make_first] Error 2
[root@qd:/home/han/Downloads/lumina]# 

Then I came to know that it has been removed from the source.... Please enlighten me thanks.

**Comment by rodlie** [comment]
Remove lumina-calculator and lumina-pdf from https://github.com/lumina-desktop/lumina/blob/master/src-qt5/desktop-utils/desktop-utils.pro

**Comment by beanpole135** [comment]
Fixed! https://github.com/lumina-desktop/lumina/commit/05f260c7363ee9bcc67d6897a33a15cb0b2c2964

Because Lumina now has it's own organization on GitHub and we don't **need** to shove everything into a single repository, we are gradually splitting out all of the desktop utilities into their own repositories. Lumina Calculator and Lumina PDF are just the first two utilities that we have split out:
* https://github.com/lumina-desktop/lumina-calculator
* https://github.com/lumina-desktop/lumina-pdf
