### ISSUE TITLE
How to test lumina-checkpass

### ISSUE THREAD

**Issue by romildo** [lumina-desktop/lumina#774]
I am updating the lumina package for NixOS, and I would like to know how to test `lumina-checkpass`, to see if it works as expected.

**Comment by q5sys** [comment]
Let me investigate this and get back to you. (Sorry for not seeing your issue until now)

**Comment by q5sys** [comment]
I spoke with Ken about this and I have a bit more to report.  Turns out lumina-checkpass was a utility that he started to write for the unified desktop ( aka Lumina 2.0) that would be used with the new Lumina Window Manager.  it's not used currently and so isn't needed.  I'm going to be disabling it from the 1.6.2 release that'll be coming out soon.  So you can go ahead and disable that from the NixOS builds as well for 1.6.1. Hopefully by the end of the month, but it might get pushed back to sometime in December.  All depends on how much time I'm able to scrape together.

Unrelated to checkpass, if there's anything I can do upstream to help your packaging efforts let me know.  As long any requested changes wont cause issues with any other OS (BSDs) or any other distros, I'm happy to do what I can to help out downstream packagers.  Also, if there are any specific build scripts you need for NixOS, I'm going to try to revive the port-files subdir so downstream projects can keep any special files or docs or whatever for their specific files in the upstream repo.  If there are any for NixOS, please feel free to shoot me a PR so I can include whatever.
